### PR TITLE
Change sed to not modify /etc/sudoers comments

### LINKED ISSUE #79: sed in Vagrant kickstarts matches extra line
This sed expression in `vagrant/centos6.ks` and `vagrant/centos7.ks`:

```
sed -i "s/^.*requiretty/#Defaults requiretty/" /etc/sudoers
```

matches both:

```
Defaults    requiretty
```

as well as the following comment shortly after:

```
# changed in order to be able to use sudo without a tty. See requiretty above.
```

Assuming the latter is not desired, #78 is a trivial fix to address this.

### PR DESCRIPTION
**Pull request by mvermaes**
This should fix #79 by only matching non-comment lines.

### CODE REVIEW

**Comment by kbsingh** [comment]
lgtm, thanks.

@lpancescu thoughts ?

**Comment by kbsingh** [comment]
ok to test

**Comment by lpancescu** [comment]
I just extracted the original `/etc/sudoers` from the *sudo* packages in CentOS Linux 6 and 7, to take a closer look. There is no `requiretty` line at all in CentOS Linux 6.8, so I would propose the following:
- remove the call to sed from `centos6.ks`;
- use `sed -i 's%^Defaults\s\+requiretty$%# This breaks Vagrant, see https://github.com/mitchellh/vagrant/issues/1482\n# &%' /etc/sudoers` in `centos7.ks`

I see that `requiretty` was already removed by Red Hat in Fedora 20 (see Fedora bug #1020147). Maybe this is why 6.8 doesn't have it anymore? I'm curious if 7.3 still has that configuration line in `/etc/sudoers`; if not, we could remove that line from `centos7.ks` after switching to a 7.3 base.

https://bugzilla.redhat.com/show_bug.cgi?id=1020147

**Comment by mvermaes** [comment]
It looks like it's fixed in sudo-1.8.6p7-18.el7, see https://bugzilla.redhat.com/show_bug.cgi?id=1196451 . I hadn't realized it had already been removed in 6.8.

I've updated to include your suggestions, but feel free to close this request and we can just wait until RHEL 7.3 to see if it can be dropped completely.

**Comment by lpancescu** [comment]
@mvermaes Thanks! It's just a cosmetic issue, so I'm okay both ways (we could merge it, if we already invested the time - this would also allow us to mark issue #78 as fixed).

With RHEL betas typically taking around two months, plus some additional delay in rebuilding, I guess we might have another 2-3 monthly Vagrant releases until we get the sudo fix.

**Comment by mvermaes** [comment]
I'll leave it up to you then. As you said, it's only cosmetic anyway - it just bothered me that it wasn't quite correct :)

**Comment by kenfusion** [comment]
Another way is to leave /etc/sudoers alone all together and put this in the /etc/sudoers.d/vagrant file which you already have created:

`echo "Defaults:vagrant !requiretty" >> /etc/sudoers.d/vagrant

`

**Comment by mvermaes** [comment]
Good point, I think that would have been a better way to handle it.

In any case, I tested on RHEL 7.3 and it includes sudo 1.8.6p7-20 which has removed this line per the [ticket](https://bugzilla.redhat.com/show_bug.cgi?id=1196451). Closing the issue.

**Pull request closed without merging**
