### PR TITLE
Add Kickstart for CentOS 8 cloud image

### PR DESCRIPTION
**Pull request by cgoncalves**

### CODE REVIEW

**Review by truatpasteurdotfr — COMMENTED** [review]
```
repo --name="BaseOS" --baseurl="http://mirror.centos.org/centos/8/BaseOS/x86_64/os/" --cost=100
```
is not needed, it's already in the --url link

updates no longer exists, everything is pushed into "os"

**Comment by ianw** [comment]
How does this relate to the builds I found at https://koji.mbox.centos.org/koji/packageinfo?packageID=2960 ?

**Comment by kbsingh** [comment]
@ianw does not

to help move this forward, let me import the ks used to build that image, and we can rebase / take it from there

**Comment by vholer** [comment]
Hello guys, don't take it bad, but is there any progress on C8 cloud image? Not having an official cloud image even after 2 weeks looks like a big miss to me. For sure, anybody can build image on his own, but, official image is official image... Thank you!!

**Comment by breisig** [comment]
I tried using this KS file (with packer) to build an image and then tried to amazon-import the image but the import image fails with the usual.

```
ClientError: Unable to determine kernel version., error: ResourceNotReady: failed waiting for successful resource state
```

**Comment by BOPOHA** [comment]
I also suggest deleting `NetworkManager*` at all.
Instead, you can use `network-scripts` package. 
systemctl enable network - will do all the other things.

**Comment by breisig** [comment]
I got abit further with building this image and but when trying to import it to AWS (using amazon-import) , amazon-import says..

Unsupported kernel version 4.18.0-80.el8.x86_64

Any ideas?

**Comment by alanivey** [comment]
Regarding potentially removing `NetworkManager`... I have not tried CentOS 8 in AWS, but it was my experience that `NetworkManager` was required get the IPv6 gateway from the EC2 router advertisements to create the IPv6 default route. In troubleshooting the issue, it was observed that the RHEL7 AMI contains NetworkManager packages, and simply installing and enabling NetworkManager.service in CentOS 7 results the IPv6 route having the correct default route without configuration or interaction. I only tested with newer EC2 instance types with ENA; it might be that older instance types don't need this.

**Comment by kbsingh** [comment]
I havent looked at any of the ipv6 pieces in AWS as yet, but can poke that. Do we have any feedback from the C7 images in that regard ?

**Comment by alanivey** [comment]
We use our own AMI built-on top of the latest CentOS 7 AMI from account `410186602215` (we can't have Marketplace codes in our images), so I can speak to my experience. While I'm not using the AWS Marketplace AMI, [NetworkManager appears to be missing there too](https://github.com/CentOS/sig-cloud-instance-build/blob/823ec0c/cloudimg/CentOS-7-x86_64-hvm.ks#L201). Without `NetworkManager`, there wasn't a default service getting the router advertisements for the IPv6 gateway for the default route. This was a few months ago; this is from my notes:

Without NetworkManager, the default IPv6 route solution is:

```
$ yum -y install radvd
$ radvdump
# Run for a moment and the comment output in the first three lines will contain the gateway IPv6 address

# Add the route manually:
$ ip -6 route add default via fe80::31:4cff:dead:beef dev eth0
```

For adding route on reboot:
```
$ echo 'default via fe80::31:4cff:dead:beef dev eth0' > /etc/sysconfig/network-scripts/route6-eth0
$ chmod 644 /etc/sysconfig/network-scripts/route6-eth0
```

This is not ideal as you need to get a real value from the VPC and that doesn't work with making a portable AMI.

RHEL 7 appears to `yum -y install NetworkManager && systemctl enable --now NetworkManager`, so I did the same thing and called it a day. Perhaps I did something wrong there.

I only bring it up in this issue in case something similar is needed with CentOS 8.

**Comment by BOPOHA** [comment]
> Without `NetworkManager`, there wasn't a default service getting the router advertisements for the IPv6 gateway for the default route. This was a few months ago; this is from my notes:

It is the bug in the cloud-init package, hardcoded 'IPV6_AUTOCONF=no':

```
# file /usr/lib/python*/site-packages/cloudinit/net/sysconfig.py
            # Now generate the cloud-init portion of sysconfig/network
            netcfg.extend([_make_header(), 'NETWORKING=yes'])
            if network_state.use_ipv6:
                netcfg.append('NETWORKING_IPV6=yes')
                netcfg.append('IPV6_AUTOCONF=no')
```

Look more https://bugs.centos.org/view.php?id=14760 and here https://bugs.launchpad.net/cloud-init/+bug/1808647

There are a few walkarouds:
- cloud-init [bootcmd](https://github.com/obscureorganization/obscure-scripts/blob/master/cloud-init-centos-7-ipv6.yml#L52-L54)
- durty hack with [patching](https://github.com/irvingpop/packer-chef-highperf-centos-ami/blob/master/create_base_ami/create_base_ami.sh#L120) cloud-init [upgrade will broke network]
- wait for a  new version cloud-init 19.4+
- [disable network configuration](https://cloudinit.readthedocs.io/en/latest/topics/network-config.html#disabling-network-configuration) by cloud-init [like me](https://github.com/BOPOHA/packer-centos8-ami/blob/0a54c48857dfe1e43a5c82a08375c1e03f42ed1c/provision.bash#L71-L74)

**Pull request closed without merging**
