### PR TITLE
Support CentOS6 i386

### PR DESCRIPTION
**Pull request by ericcurtin**
It's still a popular platform. Probably the most popular i386 that
isn't officially supported right now.

### CODE REVIEW

**Comment by ericcurtin** [comment]
??

https://www.youtube.com/watch?v=vATndqkDTGs

**Comment by jperrin** [comment]
It's Thanksgiving in the US, so right now probably not. I'll take a look at this tomorrow when I'm back

**Comment by ericcurtin** [comment]
Yes, apologies, I should have realized that. Thanks @jperrin

**Comment by jperrin** [comment]
Looks okay to me.

**Comment by ericcurtin** [comment]
Thanks for getting around to this @jperrin 

Is there anything I can do to further push this along, anymore PRs to open? Will the image appear somewhere in here eventually along with the CentOS 7 one? https://hub.docker.com/u/i386/centos

I don't actually need the CentOS 7 one personally...

Judging from #108 I could be waiting I guess :(

**Comment by jperrin** [comment]
This should be in place now -> https://github.com/docker-library/official-images/pull/3759

**Comment by ericcurtin** [comment]
Thanks @jperrin and @yosifkit

Tested the i386/centos:6 image this morning... Works great!

**Pull request merged**
