### PR TITLE
Wait for CBS to finish

### PR DESCRIPTION
**Pull request by lpancescu**
Please do not merge this yet, need to add an optional parameter

### CODE REVIEW

**Comment by lpancescu** [comment]
Retest this please

**Comment by lpancescu** [comment]
Retesting

**Comment by lpancescu** [comment]
Attempt to directly extract the full path of the images

**Comment by lpancescu** [comment]
Yet another test for writing images

**Comment by lpancescu** [comment]
PR trigger again

**Comment by bstinsonmhk** [comment]
retest

**Comment by bstinsonmhk** [comment]
test this please

**Comment by bstinsonmhk** [comment]
lgtm, nice work on the CI jobs so far

**Comment by kbsingh** [comment]
Lgtm

**Comment by lpancescu** [comment]
Please test again

**Pull request merged**
